services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    command:
      - -c
      - /envoy.yaml
    volumes:
      - ./envoy.yaml:/envoy.yaml
      - ./plugin.wasm:/plugin.wasm
    ports:
    - 8080:8080
    - 9901:9901
