services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - -c
      - /envoy.yaml
    volumes:
      - ./envoy.yaml:/envoy.yaml
      - ./plugin.wasm:/plugin.wasm
    ports:
      - 8080:8080
      - 15000:15000
    deploy:
      resources:
        limits:
          memory: 10G